version: '3.8'

services:
  jupyter-lab:
    container_name: jupyter-lab
    image: quay.io/robbins/devtools/rer_ml_jupyterlab:latest
    command: start-notebook.py --NotebookApp.token='' --no-browser --ip=0.0.0.0
    ports:
      - "8888:8888"
    volumes:
      - $HOME/projects:/home/jovyan/work
    user: root
    environment:
      - GRANT_SUDO=yes
      - NB_UID=${USER_ID}
      - NB_GID=${USER_GID}
