services:
  ml-jupyter:
    image: quay.io/robbins/ml-jupyter-gpu:latest
    container_name: ml-jupyter-gpu
    command: start-notebook.py --NotebookApp.token='' --no-browser --ip=0.0.0.0
    ports:
      - 8888:8888
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - /home/rerobbins/projects:/home/jovyan/work
      - /models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [compute, utility]
