services:
  jupyter-unstructured:
    image: quay.io/robbins/ml-jupyter-unstructured-gpu:latest
    ports:
      - "8888:8888"
    volumes:
      - /path/to/unstructured-data:/home/jovyan/data  # Persist unstructured data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    networks:
      - unstructured-net

  additional-service:  # Example additional container for unstructured work
    image: some/other-image:latest
    environment:
      - SOME_ENV_VAR=some_value
    networks:
      - unstructured-net

networks:
  unstructured-net:
    driver: bridge

