services:
  ml-jupyter:
    image: quay.io/robbins/ml-jupyter:latest
    container_name: ml-jupyter
    command: start-notebook.py --NotebookApp.token='' --no-browser --ip=0.0.0.0
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - $HOME/projects:/home/jovyan/work
